#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V VI VII VIII
bspc monitor HDMI-1 -d IX X
bspc monitor eDP-1 -s HDMI-1

#BSPDIR="$HOME/.config/bspwm/"
#export PATH="${PATH}:$BSPDIR/scripts/"

~/.config/bspwm/scripts/autostart.sh &
#sxhkd -c "$BSPDIR"/sxhkdrc &

bspc config window_gap          	8
bspc config border_width        	1
bspc config split_ratio			0.52

bspc config top_padding			0
bspc config bottom_padding		0
bspc config left_padding 		0
bspc config right_padding 		0

bspc config remove_disabled_monitors 	true
bspc config merge_overlapping_monitors	true

bspc config gapless_monocle 		true
bspc config borderless_monocle		true
bspc config presel_feedback		true
bspc config auto_alternate		true

bspc config pointer_follows_focus	false
bspc config focus_follows_pointer 	true
bspc config pointer_follows_windows	true
bspc config pointer_follows_monitor 	true

bspc config pointer_action1 		move
bspc config pointer_action2 		resize_side
bspc config pointer_action3 		resize_corner

bspc config normal_border_color 	"#FF0000"
bspc config focused_border_color	"#000000"
bspc config presel_feedback_color	"#000000"
								
#==============================================================#
#                         DESKTOP APPS                         #
#==============================================================#

# Desktop II
bspc rule -a Chromium desktop=II
bspc rule -a Google-chrome desktop=II follow=on
bspc rule -a LibreWolf desktop=II follow=on
bspc rule -a firefox desktop=II follow=on

# Desktop III
bspc rule -a Nemo desktop=III follow=on

# Desktop IV
bspc rule -a Joplin desktop=IV follow=on focus=off
bspc rule -a Nvim desktop=IV follow=on

# Desktop V
bspc rule -a Inkscape desktop=V
bsoc rule -a Vscodium desktop=V follow=off
bspc rule -a VirtualBox-Manager desktop=V follow=on state=floating
bspc rule -a Alacritty desktop=V follow=on

# Desktop VI
bspc rule -a Zapzap desktop=VI follow=off
bspc rule -a TelegramDesktop desktop=VI follow=off focus=off
bspc rule -a BlueMail desktop=VI follow=off focus=off

# Desktop VII
bspc rule -a Cmus desktop=VII
bspc rule -a Exaile desktop=VII
bspc rule -a Eog desktop=VII follow=on

# Desktop VIII
bspc rule -a onlyoffice-desktopeditors desktop=VIII
bspc rule -a wps desktop=VIII

# Free Desktops
bspc rule -a Conky state=floating follow=on manage=off
