#!/bin/sh

NVIM=$HOME/.config/nvim/init.vim
BSPWM=$HOME/.config/bspwm/bspwmrc
SXHKD=$HOME/.config/sxhkd/sxhkdrc
ZSH=$HOME/.zshrc
POLYBAR=$HOME/.config/polybar/config.ini
AUTOSTART=$HOME/.config/bspwm/scripts/autostart.sh
WINDOWS=$HOME/.config/bspwm/scripts/windows_rules.sh
PICOM=$HOME/.config/picom/picom.conf

openConfig() {
	exec kitty nvim "$1"
}

case $1 in
nvim) openConfig "$NVIM" "$1" ;;
bspwm) openConfig "$BSPWM" "$1" ;;
sxhkd) openConfig "$SXHKD" "$1" ;;
zsh) openConfig "$ZSH" "$1" ;;
polybar) openConfig "$POLYBAR" "$1" ;;
autostart) openConfig "$AUTOSTART" "$1" ;;
windows) openConfig "$WINDOWS" "$1" ;;
picom) openConfig "$PICOM" "$1" ;;
*) ;;
esac
